;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
;NORD
background = #2e3440
background-alt = #3b4252
foreground = #e5e9f0
primary = #81a1c1
secondary = #88c0d0
fourtiary = #a3be8c
tertiary = #b48ead
fiftiary = #ebcb8b
sixtiary = #d08770
alert = #bf616a
disabled = #4c566a
blue = #00FFFF

[bar/bar]
width = 100%
height = 24pt
radius = 6

; dpi = 96

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3pt

border-size = 4pt
border-color = #00000000

padding-left = 0
padding-right = 1

module-margin = 1

separator = |
separator-foreground = ${colors.disabled}

font-0 = monospace;2

modules-left = xworkspaces xwindow
modules-right = filesystem battery pulseaudio memory cpu wlan date

cursor-click = pointer
cursor-scroll = ns-resize

enable-ipc = true

; tray-position = right

; wm-restack = generic
; wm-restack = bspwm
; wm-restack = i3

; override-redirect = true

[module/xworkspaces]
type = internal/xworkspaces
enable-scroll = true
reverse-scroll = true
label-active = %name%
label-active-background = ${colours.background-alt}
label-active-foreground = ${colours.foreground}
label-active-underline= ${colours.fiftiary}
label-active-padding = 1
label-occupied = %name%
label-occupied-padding = 1
label-urgent = %name%
label-urgent-background = ${colours.alert}
label-urgent-padding = 1
label-empty = %name%
label-empty-foreground = ${colours.disabled}
label-empty-padding = 1

[module/xwindow]
type = internal/xwindow
format-background = ${colours.background}
format-foreground = ${colours.foreground}
format-underline = ${colours.foreground}
label = 󱂬 %title%
label-maxlen = 60
label-empty = No windows available
label-empty-underline = ${colours.disabled}
label-empty-foreground = ${colours.disabled

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%

label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.disabled}

[module/pulseaudio]
type = internal/pulseaudio
interval = 3
format-volume =  <label-volume> <bar-volume>
format-volume-underline = ${colours.tertiary}
format-volume-foreground = ${colours.tertiary}
label-muted =  muted
label-muted-foreground = ${colours.disabled}
bar-volume-width = 10
bar-volume-indicator = |
bar-volume-fill = ─
bar-volume-empty = ─

[module/xkeyboard]
type = internal/xkeyboard
blacklist-0 = num lock

label-layout = %layout%
label-layout-foreground = ${colors.primary}

label-indicator-padding = 2
label-indicator-margin = 1
label-indicator-foreground = ${colors.background}
label-indicator-background = ${colors.secondary}

[module/memory]
type = internal/memory
interval = 5
warn-percentage = 90
format = RAM <label> <bar-used>
format-underline = ${colours.fiftiary}
format-foreground = ${colours.fiftiary}
bar-used-indicator = |
bar-used-width = 10
bar-used-fill = ─
bar-used-empty = ─

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = "CPU "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected =  %ifname% disconnected
label-connected-foreground = ${colours.sixtiary}
label-connected-underline = ${colours.sixtiary}
label-disconnected-foreground = ${colours.disabled}

[module/wlan]
inherit = network-base
interface-type = wireless
label-connected =  %essid%

[module/eth]
inherit = network-base
interface-type = wired
label-connected = %{F#F0C674}%ifname%%{F-}

[module/date]
type = internal/date
date = %Y-%m-%d%
time = %H:%M
format =  <label>
format-underline = ${colours.sixtiary}
format-foreground = ${colours.sixtiary}
label = %date% - %time%
label-font = 2

[module/battery]
type = internal/battery
interval = 30
format-prefix = "BAT: "
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format = BATTERY <label-percentage>

format-charging = <label-charging>
format-charging-prefix = %{T10}%{T-}
format-charging-prefix-background = ${colors.blue}
format-charging-prefix-foreground = ${colors.background}
format-charging-prefix-padding = 1
label-charging = %{T2}%percentage%%%{T-}
label-charging-background = ${colors.background-alt}
label-charging-padding = 1

format-discharging = <label-discharging>
format-discharging-prefix = %{T10}%{T-}
format-discharging-prefix-background = ${colors.blue}
format-discharging-prefix-foreground = ${colors.background}
format-discharging-prefix-padding = 1
label-discharging = %{T2}%percentage%%%{T-}
label-discharging-background = ${colors.background-alt}
label-discharging-padding = 1

format-full = <label-full>
format-full-prefix = %{T10}%{T-}
format-full-prefix-background = ${colors.blue}
format-full-prefix-foreground = ${colors.background}
format-full-prefix-padding = 1
label-full = %{T2}%percentage%%%{T-}
label-full-background = ${colors.bg-alt}
label-full-padding = 1

[settings]
screenchange-reload = true
pseudo-transparency = true

; vim:ft=dosini
